#!/bin/sh
#
# Init script for payload power
#

gpioPayloadPower=103

setGpio()
{
    gpio=$1
    value=$2
    /usr/bin/gpiotest $gpio o $value
}

start()
{
    setGpio $gpioPayloadPower 1
}

stop()
{
    setGpio $gpioPayloadPower 0
}

restart() {
    stop
    start
}

case "$1" in
    start)
  	start
	;;
    stop)
  	stop
	;;
    restart|reload)
  	restart
	;;
    *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
