#!/bin/sh
#

DATE_FILE=/data/fake_date
SERIAL=`cat /proc/cpuinfo | grep Serial | sed -e 's/Serial[ \t]*:[ \t]*0*//'`
CLIENTID=board$SERIAL
CLIENTID_HEX=`echo -n "$CLIENTID" | od -A n -t x1 | sed 's/ //g'`
REVISION=`echo $SERIAL | sed -e 's/[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]$//'`
UMB=0
if [ "$REVISION" != "" ] && [ "$REVISION" -ge "3" ]; then
    UMB=`/usr/bin/gpiotest 221 i`
fi

MSERIAL=`cat /proc/cpuinfo | grep Serial | sed -e 's/Serial[ \t]*:[ \t]*//'`
LAST_IND=`expr ${#MSERIAL} - 2`
MID_IND=`expr ${#MSERIAL} - 4` 
MACADDR="00:02:0A:00:${MSERIAL:$MID_IND:2}:${MSERIAL:$LAST_IND:2}"

start() {
   if [ "$SERIAL" = "" ] || [ "$UMB" = "0" ] ; then
      echo -n Starting ethernet...
      if [ "$SERIAL" = "" ] ; then
        ifconfig eth0 192.168.0.100 netmask 255.255.255.0 
      	#start-stop-daemon -S -b -x /sbin/udhcpc -- -x 0x3d:$CLIENTID_HEX --interface=eth0
      	#/sbin/udhcpc -x 0x3d:$CLIENTID_HEX --interface=eth0
      	#/usr/sbin/ntpd -q -n -d -p ntp.nasa.gov
         echo -n
      else
         ifconfig eth0 192.168.0.100 netmask 255.255.255.0 
#         ifconfig eth0 down
#         ifconfig eth0 down hw ether $MACADDR
#         ifconfig eth0 hw ether $MACADDR
#     	start-stop-daemon -S -b -x /sbin/udhcpc -- -x 0x3d:$CLIENTID_HEX --interface=eth0
      fi

      if [ -x /sbin/polysat/ethComm ] ; then
          HERE=`pwd`
          cd /sbin/polysat
          start-stop-daemon -S -b -x ./ethComm
          cd $HERE
      fi
      echo OK
   fi
}

stop() {
   killall udhcpc
   killall ethComm
   ifconfig eth0 down
}

restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

