#!/bin/sh
#
# Run the detumbling operation the very first time we deploy
#

start()
{
    initialDeployFlag="/data/mtCtlInit.flag"
    if [ -e "$initialDeployFlag" ]; then
        return 0
    fi
    echo -n "Launching initial MT Detumbling operation..."
    /usr/local/cmds/cmdMtCtl -i&
    echo "OK"
}

stop()
{
    echo "Done"
}

restart()
{
    stop
    start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
